import { NextRequest, NextResponse } from "next/server"
import { connectToDatabase } from "@/lib/mongodb"
import { decrypt } from "@/lib/encryption"

function generateOTP(): string {
  return Math.floor(1000 + Math.random() * 9000).toString()
}

export async function POST(request: NextRequest) {
  try {
    const { email, type } = await request.json()

    if (!email || !type) {
      return NextResponse.json(
        { error: "Email and type are required" },
        { status: 400 }
      )
    }

    if (!["signup", "forgot-password"].includes(type)) {
      return NextResponse.json(
        { error: "Invalid OTP type" },
        { status: 400 }
      )
    }

    const { db } = await connectToDatabase()
    const usersCollection = db.collection("users")
    const otpCollection = db.collection("otp_attempts")

    // Check if user exists (for forgot-password type)
    let userName = "User"
    if (type === "forgot-password") {
      const user = await usersCollection.findOne({ email: email.toLowerCase() })
      if (!user) {
        return NextResponse.json(
          { error: "No account found with this email" },
          { status: 404 }
        )
      }
      userName = user.username || "User"
    } else {
      // For signup, try to get username from pending signup
      const pendingUser = await usersCollection.findOne({ email: email.toLowerCase() })
      if (pendingUser) {
        userName = pendingUser.username || "User"
      }
    }

    // Generate OTP
    const otp = generateOTP()
    const expiresAt = new Date(Date.now() + 10 * 60 * 1000) // 10 minutes

    // Store OTP in database
    await otpCollection.updateOne(
      { email: email.toLowerCase(), type },
      {
        $set: {
          email: email.toLowerCase(),
          type,
          otp,
          expiresAt,
          createdAt: new Date(),
          attempts: 0,
        },
      },
      { upsert: true }
    )

    // Get API key from environment
    const apiKey = process.env.SEND_EMAIL_API_KEY
    if (!apiKey) {
      return NextResponse.json(
        { error: "Email service not configured. Please contact support." },
        { status: 500 }
      )
    }

    // Get the base URL (for public logo)
    const baseUrl = process.env.MAILSEND_APP_URL

    // Determine email subject and purpose
    const subject =
      type === "forgot-password"
        ? "Reset Your Password - OTP Verification"
        : "Verify Your Email - OTP Verification"
    
    const purpose = type === "forgot-password" ? "Password Reset" : "Email Verification"

    // Create professional HTML template with logo from public folder
    const htmlContent = `
      <div style="font-family: Arial, sans-serif; max-width: 500px; margin: auto; padding: 20px; border-radius: 8px; background-color: #f9f9f9; border: 1px solid #ddd;">
        
        <!-- Header Section -->
        <div style="text-align: center; background-color: #030711; padding: 15px; border-radius: 8px 8px 0 0;">
          <img src="https://cdn.phototourl.com/uploads/2026-02-01-143a4d36-7a1a-45be-aa0e-5670b460d494.png" alt="EmailService Logo" style="max-width: 80px; height: auto;">
          <h2 style="color: #ffffff; margin: 10px 0;">OTP Verification</h2>
        </div>

        <!-- OTP Message -->
        <div style="background-color: #ffffff; padding: 20px; border-radius: 0 0 8px 8px; text-align: center;">
          <p style="font-size: 16px;">Dear <strong>${userName}</strong>,</p>
          <p>Your OTP for <strong>${purpose}</strong> is:</p>
          
          <div style="background-color: #f3f4f6; padding: 15px; border-radius: 5px; margin-top: 10px; text-align: center;">
            <h2 style="color: #030711; font-size: 32px; margin: 0; letter-spacing: 5px;">${otp}</h2>
            <p style="margin-top: 5px; color: #666; font-size: 14px;">This OTP expires in 10 minutes.</p>
          </div>

          <p style="text-align: center; color: gray; font-size: 12px; margin-top: 20px;">
            If you did not request this OTP, please ignore this email.<br>
            Thank you, <br>EmailService Team
          </p>
        </div>

        <hr style="border: none; border-top: 1px solid #ddd; margin: 20px 0;">

        <!-- Footer -->
        <p style="color:gray; font-size:12px; text-align: center;">This is an autogenerated message. Please do not reply to this email.</p>
      </div>
    `

    // Call the send-email API with the OTP email
    const emailResponse = await fetch(
      `${baseUrl}/api/send-email`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${apiKey}`,
        },
        body: JSON.stringify({
          from: `noreply@emailservice.local`,
          to: email,
          subject,
          html: htmlContent,
        }),
      }
    )

    if (!emailResponse.ok) {
      const errorData = await emailResponse.json()
      throw new Error(errorData.error || "Failed to send OTP email")
    }

    return NextResponse.json({
      message: `OTP sent to ${email}`,
      expiresIn: 600, // 10 minutes in seconds
    })
  } catch (error) {
    console.error("OTP generation error:", error)
    return NextResponse.json(
      { error: "Failed to generate OTP" },
      { status: 500 }
    )
  }
}
